services:
  - type: web
    name: swingmusic
    env: docker
    dockerfilePath: ./Dockerfile
    dockerComposePath: ./docker-compose.yml
    envVars:
      - key: SWINGMUSIC_APP_VERSION
        value: 1.0.0
    buildCommand: docker-compose build
    startCommand: docker-compose up
    ports:
      - port: 1970
        handlers:
          - http
    volumes:
      - name: music
        mountPath: /music
      - name: config
        mountPath: /config
